ktm/btm/urls.py
from django.urls import path
from btm import views

app_name= 'btm'

urlpatterns=[
path('register',views.register,name='register'),
path('user_login',views.user_login,name='user_login')
]

ktm/ktm/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from btm import views

urlpatterns = [
    path('',views.index,name='index'),
    path('admin/', admin.site.urls),
    path('btm/',include('btm.urls')),
    path('logout/',views.user_logout,name='logout'),
    path('special/',views.special,name='special')
]

ktm/btm/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class UserProfileInfo(models.Model):
     user = models.OneToOneField(User,on_delete=models.CASCADE)
     # additonal classes
     portfolio=models.URLField(blank=True)
     profile_pic = models.ImageField(upload_to='profile_pics',blank=True)


     def __str__(self):
         return self.user.username

ktm/btm/forms.py
from django import forms
from django.contrib.auth.models import User
from btm.models import UserProfileInfo


class UserForm(forms.ModelForm):
     password = forms.CharField(widget=forms.PasswordInput())
     class Meta():
          model = User
          fields =('username','email','password')

class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model=UserProfileInfo
        fields=('portfolio','profile_pic')

ktm/btm/views.py
from django.shortcuts import render
from btm.forms import UserForm,UserProfileInfoForm

from django.contrib.auth import authenticate,login,logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls  import reverse
from django.contrib.auth.decorators import login_required

# Create your views here.
def index(request):
    return render(request,'btm/index.html')
@login_required
def special(request):
    return HttpResponse("you are logged in mofo")

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

def  register(request):

    registered=False

    if request.method=="POST":
         user_form = UserForm(data=request.POST)
         profile_form = UserProfileInfoForm(data=request.POST)

         if user_form.is_valid() and profile_form.is_valid():
             user=user_form.save()
             user.set_password(user.password)
             user.save()

             profile=profile_form.save(commit=False)

             profile.user =user
             if 'profile_pic' in request.FILES:
                 profile.profile_pic = request.FILES['profile_pic']


             registered=True

         else:
               print(user_form.errors,profile_form.errors)
    else:
          user_form=UserForm()
          profile_form=UserProfileInfoForm()
    dict1= {'user':user_form,'profile':profile_form,'registered':registered }
    return render(request,'btm/registration.html',context=dict1)





def user_login(request):

    if request.method=="POST":
        username =request.POST.get('username')
        password =request.POST.get('password')

        user= authenticate(username=username,password=password)

        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('index'))
            else:
                return HttpResponseRedirect("account not active")
        else:
            print("someone tried to login in and failed")
            print("username: {} and password".format(username,password))
            return HttpResponse("invalid login details")
    else:
        return render(request,'btm/login.html')

ktm/templates/btm/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  </head>
  <body>
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <ul class="nav navbar-nav">
          <li><a class="navbar-brand" href="{% url 'index'%}">DJANGO</a></li>
          <li><a class="navbar-link" href="{% url 'admin:index'%}"></a>Admin</li>
          <li><a class="navbar-link" href="{% url 'btm:register'%}">register</a></li>

          {%if user.is_authenticated %}
          <li> <a class='navbar-link' href="{% url 'logout'%}">logout</a> </li>
          {%else%}
          <li> <a class ="navbar-link"href="{% url 'btm:user_login'%}">login</a> </li>
          {% endif %}

        </ul>
      </div>
    </nav>
    <div class="container">
      {% block body%}
      {% endblock %}


    </div>

  </body>
</html>

ktm/templates/btm/index.html
{% extends "btm/base.html" %}
{% block body}
<div class="jumbotorn">
  <h1>Django level five</h1>

</div>
{% endblock}

ktm/templates/btm/login.html
{% extends 'btm/base.html'%}
{%block body%}
<div class="jumbotron">
  <h3>Please login in </h3>
  <a href="{% url 'btm:register'%}" > <h4>Register</h4></a>
  <form  action="{% url 'btm:user_login' %}" method="post">
    {% csrf_token %}
    <label for="Username">Username:</label>
    <input type="text" name="Username"placeholder="Enter Username" >
    <label for="Password">Password:</label>
    <input type="password" name=" password">

    <input type="submit" name="" value="Login">
  </form>
</div>
{%endblock%}

ktm/templates/btm/registration.html
{% extends "btm/base.html" %}
{% load static %}
{% block body %}
<div class="jumbotron">
  {% if registered %}
  <h1>Thank you for registrating with us</h1>
  {% else %}
  <h1>register here</h1>
  <h3> fill out the form</h3>
  <form enctype="multipart/form-data" method="post">
    {% csrf_token%}
    {{ user.as_p }}
    {{ profile.as_p }}
    <input type="submit" name="" value="register">
  </form>
  {% endif%}

</div>

{% endblock%}